system:
    sillonbol:
        database:
            type: mysql
            user: '***********'
            password: '***********'
            server: '***********'
            database_name: '***********'