sillonbol_web_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SillonbolWebBundle:Default:index }

contact:
    path: contacto
    defaults: { _controller: SillonbolWebBundle:Contact:index }

contact_process:
    path: ok
    defaults: { _controller: SillonbolWebBundle:Contact:ok }
    
rss:
    path: rss
    defaults: { _controller: SillonbolWebBundle:Feed:index, _format: rss }