http_cache:
    purge_type: local
siteaccess:
    default_siteaccess: www
    list:
        - www
        - administrador
    groups:
        sillonbol:
            - www
            - administrador
    match:
        URIElement: '1'
system:
    www:
        content:
            view_cache: true
            ttl_cache: true
            default_ttl: 14400
        fieldtypes:
            ezxml:
                custom_tags:
                    - { path: %kernel.root_dir%/../src/Sillonbol/WebBundle/Resources/custom_tags.xsl, priority: 10 }

