system:
    www:
        location_view:
            featured:
                article:
                    controller: "SillonbolWebBundle:Web:showArticle"
                    template: "SillonbolWebBundle:featured:article.html.twig"
                    match:
                        Identifier\ContentType: [article, blog_post]
            line:
                article:
                    controller: "SillonbolWebBundle:Web:showArticle"
                    template: "SillonbolWebBundle:line:article.html.twig"
                    match:
                        Identifier\ContentType: [article, blog_post]
            rss:
                article:
                    controller: "SillonbolWebBundle:Web:showArticle"
                    template: "SillonbolWebBundle:rss:article.html.twig"
                    match:
                        Identifier\ContentType: [article, blog_post]
            full:
                home:
                    template: "SillonbolWebBundle:full:home.html.twig"
                    match:
                        Identifier\ContentType: [frontpage]
                article:
                    controller: "SillonbolWebBundle:Web:showArticle"
                    template: "SillonbolWebBundle:full:article.html.twig"
                    match:
                        Identifier\ContentType: [article, blog_post]
                page:
                    template: "SillonbolWebBundle:full:page.html.twig"
                    match:
                        Identifier\ContentType: [pagina]
                subcategoria:
                    controller: "SillonbolWebBundle:Web:categoryList"
                    match:
                        Identifier\ContentType: [subcategoria]
        image_variations:
            featured:
                reference: null
                filters:
                    - { name: geometry/scalewidthdownonly, params: [640] }
                    - { name: geometry/crop, params: [400, 400, 0, 0] }
            line:
                reference: null
                filters:
                    - { name: geometry/scalewidthdownonly, params: [400] }