ezpublish:
    system:
        default:
            image_variations:
                   big:
                       reference: null
                       filters:
                           - { name: geometry/scalewidthdownonly, params: [1200] }
                           - { name: geometry/crop, params: [1200, 600, 0, 0] }
                   featured:
                       reference: null
                       filters:
                           - { name: geometry/scalewidthdownonly, params: [800] }
                           - { name: geometry/crop, params: [800, 800, 0, 0] }
                   line:
                       reference: null
                       filters:
                           - { name: geometry/scalewidthdownonly, params: [400] }
