ezpublish:
    system:
        default:
            image_variations:
                   big:
                       reference: null
                       filters:
                           - { name: geometry/scalewidthdownonly, params: [1200] }
                           - { name: geometry/crop, params: [1200, 600, 0, 0] }
                   featured:
                       reference: null
                       filters:
                           - { name: geometry/scalewidthdownonly, params: [800] }
                           - { name: geometry/crop, params: [800, 800, 0, 0] }
                   line:
                       reference: null
                       filters:
                           - { name: geometry/scalewidthdownonly, params: [400] }
                   contenido_derecha:
                       reference: null
                       filters:
                           - {name: geometry/scaledownonly, params: [250, 1500]}
                   contenido_todoancho:
                       reference: null
                       filters:
                           - {name: geometry/scaledownonly, params: [590, 1500]}
                   small:
                       reference: null
                       filters:
                           - {name: geometry/scaledownonly, params: [100, 100]}


