{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
{let data_text=cond( is_set( $#collection_attributes[$attribute.id] ), $#collection_attributes[$attribute.id].data_text, $attribute.content )}
<input class="box text" type="text" size="20" name="{$attribute_base}_data_text_{$attribute.id}" value="{cond( $data_text|ne(''), $data_text|wash( xhtml ), $attribute.contentclass_attribute.name)}" />
{/let}
{/default}
